[package]
name = "builder"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
rcl = { path = "../rcl" }
tempfile = "3.20.0"
